// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.28.2
// source: perception.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PerceptionService_ReadEconomy_FullMethodName     = "/perception.PerceptionService/ReadEconomy"
	PerceptionService_ReadBattlefield_FullMethodName = "/perception.PerceptionService/ReadBattlefield"
	PerceptionService_HealthCheck_FullMethodName     = "/perception.PerceptionService/HealthCheck"
)

// PerceptionServiceClient is the client API for PerceptionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PerceptionService — единственная граница между Go-ядром и Python CV/OCR.
// Go никогда не работает с изображениями напрямую (см. ТЗ, раздел 8.2).
type PerceptionServiceClient interface {
	// ReadEconomy — дешёвый, частый вызов: Mythium, доход, номер волны, таймер.
	// MVP (Фаза 1) реализует только этот метод.
	ReadEconomy(ctx context.Context, in *ReadEconomyRequest, opts ...grpc.CallOption) (*EconomyState, error)
	// ReadBattlefield — дорогой, редкий вызов: позиции юнитов на поле.
	// Реализуется в Фазе 2, после офлайн-датасета (см. ТЗ 8.4, Phase 2.3).
	ReadBattlefield(ctx context.Context, in *ReadBattlefieldRequest, opts ...grpc.CallOption) (*BattlefieldState, error)
	// HealthCheck — используется для индикатора "вижу поле уверенно / не уверен / не вижу" (FR5).
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type perceptionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPerceptionServiceClient(cc grpc.ClientConnInterface) PerceptionServiceClient {
	return &perceptionServiceClient{cc}
}

func (c *perceptionServiceClient) ReadEconomy(ctx context.Context, in *ReadEconomyRequest, opts ...grpc.CallOption) (*EconomyState, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EconomyState)
	err := c.cc.Invoke(ctx, PerceptionService_ReadEconomy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *perceptionServiceClient) ReadBattlefield(ctx context.Context, in *ReadBattlefieldRequest, opts ...grpc.CallOption) (*BattlefieldState, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BattlefieldState)
	err := c.cc.Invoke(ctx, PerceptionService_ReadBattlefield_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *perceptionServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, PerceptionService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PerceptionServiceServer is the server API for PerceptionService service.
// All implementations must embed UnimplementedPerceptionServiceServer
// for forward compatibility.
//
// PerceptionService — единственная граница между Go-ядром и Python CV/OCR.
// Go никогда не работает с изображениями напрямую (см. ТЗ, раздел 8.2).
type PerceptionServiceServer interface {
	// ReadEconomy — дешёвый, частый вызов: Mythium, доход, номер волны, таймер.
	// MVP (Фаза 1) реализует только этот метод.
	ReadEconomy(context.Context, *ReadEconomyRequest) (*EconomyState, error)
	// ReadBattlefield — дорогой, редкий вызов: позиции юнитов на поле.
	// Реализуется в Фазе 2, после офлайн-датасета (см. ТЗ 8.4, Phase 2.3).
	ReadBattlefield(context.Context, *ReadBattlefieldRequest) (*BattlefieldState, error)
	// HealthCheck — используется для индикатора "вижу поле уверенно / не уверен / не вижу" (FR5).
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	mustEmbedUnimplementedPerceptionServiceServer()
}

// UnimplementedPerceptionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPerceptionServiceServer struct{}

func (UnimplementedPerceptionServiceServer) ReadEconomy(context.Context, *ReadEconomyRequest) (*EconomyState, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadEconomy not implemented")
}
func (UnimplementedPerceptionServiceServer) ReadBattlefield(context.Context, *ReadBattlefieldRequest) (*BattlefieldState, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadBattlefield not implemented")
}
func (UnimplementedPerceptionServiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedPerceptionServiceServer) mustEmbedUnimplementedPerceptionServiceServer() {}
func (UnimplementedPerceptionServiceServer) testEmbeddedByValue()                           {}

// UnsafePerceptionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PerceptionServiceServer will
// result in compilation errors.
type UnsafePerceptionServiceServer interface {
	mustEmbedUnimplementedPerceptionServiceServer()
}

func RegisterPerceptionServiceServer(s grpc.ServiceRegistrar, srv PerceptionServiceServer) {
	// If the following call panics, it indicates UnimplementedPerceptionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PerceptionService_ServiceDesc, srv)
}

func _PerceptionService_ReadEconomy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadEconomyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PerceptionServiceServer).ReadEconomy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PerceptionService_ReadEconomy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PerceptionServiceServer).ReadEconomy(ctx, req.(*ReadEconomyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PerceptionService_ReadBattlefield_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadBattlefieldRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PerceptionServiceServer).ReadBattlefield(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PerceptionService_ReadBattlefield_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PerceptionServiceServer).ReadBattlefield(ctx, req.(*ReadBattlefieldRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PerceptionService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PerceptionServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PerceptionService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PerceptionServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PerceptionService_ServiceDesc is the grpc.ServiceDesc for PerceptionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PerceptionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "perception.PerceptionService",
	HandlerType: (*PerceptionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReadEconomy",
			Handler:    _PerceptionService_ReadEconomy_Handler,
		},
		{
			MethodName: "ReadBattlefield",
			Handler:    _PerceptionService_ReadBattlefield_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _PerceptionService_HealthCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "perception.proto",
}
