// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.2
// source: perception.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReadEconomyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadEconomyRequest) Reset() {
	*x = ReadEconomyRequest{}
	mi := &file_perception_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadEconomyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadEconomyRequest) ProtoMessage() {}

func (x *ReadEconomyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_perception_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadEconomyRequest.ProtoReflect.Descriptor instead.
func (*ReadEconomyRequest) Descriptor() ([]byte, []int) {
	return file_perception_proto_rawDescGZIP(), []int{0}
}

type EconomyState struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Mythium           int32                  `protobuf:"varint,1,opt,name=mythium,proto3" json:"mythium,omitempty"`
	Income            int32                  `protobuf:"varint,2,opt,name=income,proto3" json:"income,omitempty"`
	WaveNumber        int32                  `protobuf:"varint,3,opt,name=wave_number,json=waveNumber,proto3" json:"wave_number,omitempty"`
	WaveTimerSeconds  int32                  `protobuf:"varint,4,opt,name=wave_timer_seconds,json=waveTimerSeconds,proto3" json:"wave_timer_seconds,omitempty"`
	KingHpPercent     int32                  `protobuf:"varint,5,opt,name=king_hp_percent,json=kingHpPercent,proto3" json:"king_hp_percent,omitempty"`
	AllyKingHpPercent int32                  `protobuf:"varint,6,opt,name=ally_king_hp_percent,json=allyKingHpPercent,proto3" json:"ally_king_hp_percent,omitempty"`
	Confidence        float32                `protobuf:"fixed32,7,opt,name=confidence,proto3" json:"confidence,omitempty"` // 0.0–1.0, используется для FR5
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *EconomyState) Reset() {
	*x = EconomyState{}
	mi := &file_perception_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EconomyState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EconomyState) ProtoMessage() {}

func (x *EconomyState) ProtoReflect() protoreflect.Message {
	mi := &file_perception_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EconomyState.ProtoReflect.Descriptor instead.
func (*EconomyState) Descriptor() ([]byte, []int) {
	return file_perception_proto_rawDescGZIP(), []int{1}
}

func (x *EconomyState) GetMythium() int32 {
	if x != nil {
		return x.Mythium
	}
	return 0
}

func (x *EconomyState) GetIncome() int32 {
	if x != nil {
		return x.Income
	}
	return 0
}

func (x *EconomyState) GetWaveNumber() int32 {
	if x != nil {
		return x.WaveNumber
	}
	return 0
}

func (x *EconomyState) GetWaveTimerSeconds() int32 {
	if x != nil {
		return x.WaveTimerSeconds
	}
	return 0
}

func (x *EconomyState) GetKingHpPercent() int32 {
	if x != nil {
		return x.KingHpPercent
	}
	return 0
}

func (x *EconomyState) GetAllyKingHpPercent() int32 {
	if x != nil {
		return x.AllyKingHpPercent
	}
	return 0
}

func (x *EconomyState) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

type ReadBattlefieldRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadBattlefieldRequest) Reset() {
	*x = ReadBattlefieldRequest{}
	mi := &file_perception_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadBattlefieldRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadBattlefieldRequest) ProtoMessage() {}

func (x *ReadBattlefieldRequest) ProtoReflect() protoreflect.Message {
	mi := &file_perception_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadBattlefieldRequest.ProtoReflect.Descriptor instead.
func (*ReadBattlefieldRequest) Descriptor() ([]byte, []int) {
	return file_perception_proto_rawDescGZIP(), []int{2}
}

type BattlefieldState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Units         []*UnitPlacement       `protobuf:"bytes,1,rep,name=units,proto3" json:"units,omitempty"`
	Confidence    float32                `protobuf:"fixed32,2,opt,name=confidence,proto3" json:"confidence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BattlefieldState) Reset() {
	*x = BattlefieldState{}
	mi := &file_perception_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BattlefieldState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BattlefieldState) ProtoMessage() {}

func (x *BattlefieldState) ProtoReflect() protoreflect.Message {
	mi := &file_perception_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BattlefieldState.ProtoReflect.Descriptor instead.
func (*BattlefieldState) Descriptor() ([]byte, []int) {
	return file_perception_proto_rawDescGZIP(), []int{3}
}

func (x *BattlefieldState) GetUnits() []*UnitPlacement {
	if x != nil {
		return x.Units
	}
	return nil
}

func (x *BattlefieldState) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

type UnitPlacement struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UnitId        string                 `protobuf:"bytes,1,opt,name=unit_id,json=unitId,proto3" json:"unit_id,omitempty"` // соответствует id из /units API (например fire_elemental_unit_id)
	X             float32                `protobuf:"fixed32,2,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32                `protobuf:"fixed32,3,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnitPlacement) Reset() {
	*x = UnitPlacement{}
	mi := &file_perception_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnitPlacement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnitPlacement) ProtoMessage() {}

func (x *UnitPlacement) ProtoReflect() protoreflect.Message {
	mi := &file_perception_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnitPlacement.ProtoReflect.Descriptor instead.
func (*UnitPlacement) Descriptor() ([]byte, []int) {
	return file_perception_proto_rawDescGZIP(), []int{4}
}

func (x *UnitPlacement) GetUnitId() string {
	if x != nil {
		return x.UnitId
	}
	return ""
}

func (x *UnitPlacement) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *UnitPlacement) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_perception_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_perception_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_perception_proto_rawDescGZIP(), []int{5}
}

type HealthCheckResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	GameWindowDetected bool                   `protobuf:"varint,1,opt,name=game_window_detected,json=gameWindowDetected,proto3" json:"game_window_detected,omitempty"`
	CaptureHealthy     bool                   `protobuf:"varint,2,opt,name=capture_healthy,json=captureHealthy,proto3" json:"capture_healthy,omitempty"`
	Message            string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_perception_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_perception_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_perception_proto_rawDescGZIP(), []int{6}
}

func (x *HealthCheckResponse) GetGameWindowDetected() bool {
	if x != nil {
		return x.GameWindowDetected
	}
	return false
}

func (x *HealthCheckResponse) GetCaptureHealthy() bool {
	if x != nil {
		return x.CaptureHealthy
	}
	return false
}

func (x *HealthCheckResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_perception_proto protoreflect.FileDescriptor

const file_perception_proto_rawDesc = "" +
	"\n" +
	"\x10perception.proto\x12\n" +
	"perception\"\x14\n" +
	"\x12ReadEconomyRequest\"\x88\x02\n" +
	"\fEconomyState\x12\x18\n" +
	"\amythium\x18\x01 \x01(\x05R\amythium\x12\x16\n" +
	"\x06income\x18\x02 \x01(\x05R\x06income\x12\x1f\n" +
	"\vwave_number\x18\x03 \x01(\x05R\n" +
	"waveNumber\x12,\n" +
	"\x12wave_timer_seconds\x18\x04 \x01(\x05R\x10waveTimerSeconds\x12&\n" +
	"\x0fking_hp_percent\x18\x05 \x01(\x05R\rkingHpPercent\x12/\n" +
	"\x14ally_king_hp_percent\x18\x06 \x01(\x05R\x11allyKingHpPercent\x12\x1e\n" +
	"\n" +
	"confidence\x18\a \x01(\x02R\n" +
	"confidence\"\x18\n" +
	"\x16ReadBattlefieldRequest\"c\n" +
	"\x10BattlefieldState\x12/\n" +
	"\x05units\x18\x01 \x03(\v2\x19.perception.UnitPlacementR\x05units\x12\x1e\n" +
	"\n" +
	"confidence\x18\x02 \x01(\x02R\n" +
	"confidence\"D\n" +
	"\rUnitPlacement\x12\x17\n" +
	"\aunit_id\x18\x01 \x01(\tR\x06unitId\x12\f\n" +
	"\x01x\x18\x02 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x02R\x01y\"\x14\n" +
	"\x12HealthCheckRequest\"\x8a\x01\n" +
	"\x13HealthCheckResponse\x120\n" +
	"\x14game_window_detected\x18\x01 \x01(\bR\x12gameWindowDetected\x12'\n" +
	"\x0fcapture_healthy\x18\x02 \x01(\bR\x0ecaptureHealthy\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage2\x81\x02\n" +
	"\x11PerceptionService\x12G\n" +
	"\vReadEconomy\x12\x1e.perception.ReadEconomyRequest\x1a\x18.perception.EconomyState\x12S\n" +
	"\x0fReadBattlefield\x12\".perception.ReadBattlefieldRequest\x1a\x1c.perception.BattlefieldState\x12N\n" +
	"\vHealthCheck\x12\x1e.perception.HealthCheckRequest\x1a\x1f.perception.HealthCheckResponseBFH\x01ZBgithub.com/yourname/legiontd2-copilot/internal/perceptionclient/pbb\x06proto3"

var (
	file_perception_proto_rawDescOnce sync.Once
	file_perception_proto_rawDescData []byte
)

func file_perception_proto_rawDescGZIP() []byte {
	file_perception_proto_rawDescOnce.Do(func() {
		file_perception_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_perception_proto_rawDesc), len(file_perception_proto_rawDesc)))
	})
	return file_perception_proto_rawDescData
}

var file_perception_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_perception_proto_goTypes = []any{
	(*ReadEconomyRequest)(nil),     // 0: perception.ReadEconomyRequest
	(*EconomyState)(nil),           // 1: perception.EconomyState
	(*ReadBattlefieldRequest)(nil), // 2: perception.ReadBattlefieldRequest
	(*BattlefieldState)(nil),       // 3: perception.BattlefieldState
	(*UnitPlacement)(nil),          // 4: perception.UnitPlacement
	(*HealthCheckRequest)(nil),     // 5: perception.HealthCheckRequest
	(*HealthCheckResponse)(nil),    // 6: perception.HealthCheckResponse
}
var file_perception_proto_depIdxs = []int32{
	4, // 0: perception.BattlefieldState.units:type_name -> perception.UnitPlacement
	0, // 1: perception.PerceptionService.ReadEconomy:input_type -> perception.ReadEconomyRequest
	2, // 2: perception.PerceptionService.ReadBattlefield:input_type -> perception.ReadBattlefieldRequest
	5, // 3: perception.PerceptionService.HealthCheck:input_type -> perception.HealthCheckRequest
	1, // 4: perception.PerceptionService.ReadEconomy:output_type -> perception.EconomyState
	3, // 5: perception.PerceptionService.ReadBattlefield:output_type -> perception.BattlefieldState
	6, // 6: perception.PerceptionService.HealthCheck:output_type -> perception.HealthCheckResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_perception_proto_init() }
func file_perception_proto_init() {
	if File_perception_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_perception_proto_rawDesc), len(file_perception_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_perception_proto_goTypes,
		DependencyIndexes: file_perception_proto_depIdxs,
		MessageInfos:      file_perception_proto_msgTypes,
	}.Build()
	File_perception_proto = out.File
	file_perception_proto_goTypes = nil
	file_perception_proto_depIdxs = nil
}
